version = 0.1

[default.deploy.parameters]
stack_name = "Aloy"
resolve_s3 = true
s3_prefix = "Aloy"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GHTodoRepoOwner=\"cskrishna9306\" GHTodoRepoName=\"TODOs\" AlexaSkillId=\"\""
image_repositories = []

[default.global.parameters]
region = "us-west-1"
